{pkgs}:
pkgs.writeShellScriptBin "list-keybinds" ''
  # Toggle: close if the menu is already open.
  if pidof rofi > /dev/null; then
    pkill rofi
    exit 0
  fi

  # Generated by config.lua on every Hyprland load/reload (ADR-0005: binds are
  # native lua and opaque to `hyprctl binds`, so the descriptions live there).
  sheet="''${XDG_CACHE_HOME:-$HOME/.cache}/hypr-keybinds.txt"
  if [ ! -s "$sheet" ]; then
    ${pkgs.libnotify}/bin/notify-send "list-keybinds" "cheat sheet not generated yet — reload Hyprland" || true
    exit 1
  fi

  rofi -dmenu -i -p keybinds -config ~/.config/rofi/config-long.rasi < "$sheet"
''
