{
  username,
  config,
  lib,
  mkDesignSource,
  ...
}: let
  inherit
    (config.variables)
    accent0
    accent1
    browser
    terminal
    extraMonitorSettings
    extraHardwareSettings
    defaultWallpaper
    keyboardLayout
    ;

  toLua = lib.generators.toLua {};

  # The Nix-derived, host-specific values consumed by config.lua. Everything that
  # used to be `${interpolated}` into the Lua heredoc lives here instead, so the
  # bulk config (config.lua) stays a pure, hot-reloadable native file. See
  # docs/adr/0005.
  varsLua = ''
    -- Generated by Nix — edit modules/home/hyprland/config.nix, not this file.
    -- Host-specific values consumed by config.lua.
    local vars = {
      accent0        = ${toLua accent0},
      accent1        = ${toLua accent1},
      inactiveBorder = "rgba(${config.lib.stylix.colors.base01}ff)",
      browser        = ${toLua browser},
      terminal       = ${toLua terminal},
      kbVariant      = ${toLua keyboardLayout},
      wallpaper      = "/home/${username}/Pictures/Wallpapers/${defaultWallpaper}",
      monitors = {
    ${lib.concatMapStrings (m: "    { output = ${toLua m.output}, mode = ${toLua m.mode}, position = ${toLua m.position}, scale = ${m.scale} },\n") extraMonitorSettings}  },
      hardware = ${toLua extraHardwareSettings},
    }
    return vars
  '';
in {
  # Bootstrap: make hypr/*.lua requirable, then load the native config. Hyprland's
  # lua runtime exposes the `hl` global into required chunks, so config.lua/vars.lua
  # use it directly. config.lua require()s vars itself.
  wayland.windowManager.hyprland.extraConfig = ''
    -- ADR-0005: native config split out of this generated file.
    local hm_xdg_config_home = os.getenv("XDG_CONFIG_HOME") or ${toLua config.xdg.configHome}
    package.path = hm_xdg_config_home .. "/hypr/?.lua;" .. hm_xdg_config_home .. "/hypr/?/init.lua;" .. package.path
    require("config")
  '';

  # vars.lua is always Nix-generated (pure). config.lua is the native bulk: in
  # designMode it is symlinked to the working tree for live `hyprctl reload`
  # iteration; otherwise it is the in-store copy.
  xdg.configFile = {
    "hypr/vars.lua".text = varsLua;
    "hypr/config.lua".source = mkDesignSource {
      repo = "modules/home/hyprland/config.lua";
      store = ./config.lua;
    };
  };
}
